name: "Periodic quality and security analysis"

on:
  # Every monday at 09:48 UTC
  schedule:
    - cron: "48 9 * * 1"
  workflow_dispatch:

jobs:
  codeql:
    permissions:
      security-events: write
      actions: read
      contents: read
    
    uses: Steffo99/.github/.github/workflows/quality-python-codeql.yml@main
