name: "Release new version"

on:
  # Creation of a new tag starting with v
  push: 
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  build:
    uses: Steffo99/.github/.github/workflows/build-poetry.yml@main

  github:
    uses: Steffo99/.github/.github/workflows/release-poetry-github.yml@main
    needs:
      - test
      - build

  pypi:
    uses: Steffo99/.github/.github/workflows/release-poetry-pypi.yml@main
    needs:
      - test
      - build
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  portainer:
    uses: Steffo99/.github/.github/workflows/deploy-portainer.yml@main
    needs:
      - ghcrio
    secrets:
      PORTAINER_HOOK_URL: ${{ secrets.PORTAINER_HOOK_URL }}
