name: "Release new version"

on:
  # Creation of a new tag starting with v
  push: 
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  build:
    uses: Steffo99/.github/.github/workflows/build-poetry.yml@main

  github:
    uses: Steffo99/.github/.github/workflows/release-poetry-github.yml@main
    needs:
      - test
      - build

  pypi:
    uses: Steffo99/.github/.github/workflows/release-poetry-pypi.yml@main
    permissions:
      id-token: write
    needs:
      - test
      - build
