name: "Release new version"

on:
  # Creation of a new tag starting with v
  push: 
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  build:
    uses: Steffo99/.github/.github/workflows/build-poetry.yml@main

  github:
    uses: Steffo99/.github/.github/workflows/release-poetry-github.yml@main
    needs:
      - test
      - build

  # Must be explicit due to how Trusted Publishing works on PyPI!
  pypi:
    name: "Publish release on PyPI"
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    needs:
      - test
      - build
    steps:
      - name: "Download built packages from artifacts"
        uses: actions/download-artifact@v4
        with:
          name: "Build"
          path: dist/

      - name: "Upload package"
        uses: pypa/gh-action-pypi-publish@release/v1
